#!/bin/sh -eux

cd js/src

ub_install
rm -f $UB_INSTALLDIR/usr/lib/*.ajs
pushd $UB_INSTALLDIR/usr/include/mozjs-38 &&
for link in `find . -type l`; do
    header=`readlink $link`
    rm -f $link
    cp -pv $header $link
    chmod 644 $link
done &&
popd
