#!/bin/sh -eux

if [ "$UB_ARCH" = "amd64" ]; then
	tar -xzvf flash_player_npapi_linux.x86_64.tar.gz
	sofile=libflashplayer.so
else
	tar -xzvf flash_player_ppapi_linux.i386.tar.gz
	sofile=libpepflashplayer.so
fi
rm -f flash_player_ppapi_linux*.tar.gz

libdir="$UB_INSTALLDIR/usr/lib"

mkdir -p "$libdir"/adobe-flashplugin
mkdir -p "$libdir"/{firefox,mozilla}/plugins

install -m 755 $sofile "$libdir"/adobe-flashplugin/

if [ ! "$UB_ARCH" = "amd64" ]; then
install -m 644 manifest.json "$libdir"/adobe-flashplugin/
fi

ln -s ../../adobe-flashplugin/$sofile "$libdir"/firefox/plugins/
ln -s ../../adobe-flashplugin/$sofile "$libdir"/mozilla/plugins/
