#!/bin/bash -eux

function alprogi {
	cd $1
    export PREFIX=/usr
    ub_compile
    cd -
}

#előkészület
if [ "$UB_ARCH" == "amd64" ];then
KVER="$(ls -1 /lib/modules | grep x86_64)"
forras="NVIDIA-Linux-x86_64-${UB_VERSION}-no-compat32"
else
KVER="$(ls -1 /lib/modules | grep i386)"
forras="NVIDIA-Linux-x86-${UB_VERSION}"
fi
moduldir="$UB_COMPILEDIR/lib/modules/"$KVER"/kernel/drivers"
mkdir -p $moduldir
#kicsomagolás és belépés
chmod +x $forras.run
./$forras.run -x
rm *.run
cd $forras/kernel
patch -i "$UB_SRCDIR"/patches/kernel-4.14.patch.skip
patch -i "$UB_SRCDIR"/patches/kernel-4.15.patch.skip
patch -i "$UB_SRCDIR"/patches/disable-mtrr.patch.skip
patch -i "$UB_SRCDIR"/patches/silencium.patch.skip
make SYSSRC=/usr/src/linux-$KVER KERNEL_UNAME="$KVER" MODULE_ROOT=$moduldir module
#akdályok leküzdése a telepítéshez
sed -e 's/suser-sanity-check //g' -i Makefile.kbuild
sed -e 's/depmod -ae/true/g' -i Makefile.kbuild
#elkészült modul telepítése
make SYSSRC=/usr/src/linux-$KVER KERNEL_UNAME="$KVER" MODULE_ROOT=$moduldir module-install
#ez minek? De legyen..
make clean

cd ../..
alprogi settings/src/libXNVCtrl
export NV_USE_BUNDLED_LIBJANSSON=0
export CFLAGS+=' -Wno-deprecated-declarations '
alprogi settings
alprogi xconfig
