#!/bin/sh -eux

ub_replace -O3 -O2 configure.ac
./bootstrap
export BUILDCC="/usr/bin/gcc -std=gnu99"
export LUA_CFLAGS=`pkg-config --cflags lua53`
export LUA_LIBS=`pkg-config --libs lua53`
export LUAC=luac5.3
ub_compile \
	--enable-jack \
	--enable-lirc \
	--enable-nls \
	--disable-update-check \
    --enable-qt=5
