#!/bin/sh -eux

mkdir -p build-x build-w
cd build-x
    cmake \
   	-DCMAKE_INSTALL_PREFIX=/usr \
	-Ddocdir=/usr/share/doc/Packages/kodi \
	-DVERBOSE=ON \
	-DENABLE_INTERNAL_FLATBUFFERS=ON \
	-DENABLE_INTERNAL_FMT=ON \
	-DENABLE_INTERNAL_FSTRCMP=OFF \
	-DENABLE_INTERNAL_RapidJSON=OFF \
	-DJava_JAVA_EXECUTABLE=/usr/lib/java/jre/bin/java \
    -DAPP_RENDER_SYSTEM=gl \
    -DX11_RENDER_SYSTEM=gl \
    ..
ub_make
cd ../build-w
    cmake \
   	-DCMAKE_INSTALL_PREFIX=/usr \
	-Ddocdir=/usr/share/doc/Packages/kodi \
	-DVERBOSE=ON \
	-DENABLE_INTERNAL_FLATBUFFERS=ON \
	-DENABLE_INTERNAL_FMT=ON \
	-DENABLE_INTERNAL_FSTRCMP=OFF \
	-DENABLE_INTERNAL_RapidJSON=OFF \
	-DJava_JAVA_EXECUTABLE=/usr/lib/java/jre/bin/java \
    -DWAYLAND_RENDER_SYSTEM=gl \
    -DCORE_PLATFORM_NAME=wayland \
    ..
ub_make
