#!/bin/sh -eux

mkdir -p {client,server}
cd client
cmake \
    -DFORCE_INTERNAL_GME=OFF \
    -DOpenGL_GL_PREFERENCE=GLVND \
..
ub_make

cd ../server
cmake \
    -DSERVERONLY=ON \
    -DFORCE_INTERNAL_GME=OFF \
    -DOpenGL_GL_PREFERENCE=GLVND \
..
ub_make
