#!/bin/sh -eux

mkdir -p build
cd build
meson \
    --prefix=/usr \
    --buildtype=plain \
	-Dpixbuf=true \
	-Dintrospection=true \
	-Dmathjax-directory=/usr/share/yelp/mathjax \
    -Dtests=false \
    ..
samu
