#!/bin/sh -eux

ub_install

# remove execute bit from these examples, we dont want to depend on tcsh
chmod -x "$UB_INSTALLDIR"/usr/share/doc/util-linux/getopt/*

# fix version in .pc files
if [ "$UB_VERSION_HEAD2" = "$UB_VERSION" ]; then
	sed -i "s/^Version: .*$/Version: $UB_VERSION/g" "$UB_INSTALLDIR"/usr/lib/pkgconfig/*.pc
fi
# systemd kompatibilitás
for rootbin in `ls -1 $UB_INSTALLDIR/bin`;do
    ln -s ../../bin/$rootbin $UB_INSTALLDIR/usr/bin/$rootbin
done
