#!/bin/bash -eux

function alprogi {
	cd $1
    export PREFIX=/usr
    ub_compile
    cd ..
}

#előkészület
if [ "$UB_ARCH" == "amd64" ];then
KVER="$(ls -1 /lib/modules | grep x86_64)"
forras="NVIDIA-Linux-x86_64-${UB_VERSION}-no-compat32"
else
KVER="$(ls -1 /lib/modules | grep i386)"
forras="NVIDIA-Linux-x86-${UB_VERSION}"
fi
moduldir="$UB_COMPILEDIR/lib/modules/"$KVER"/kernel/drivers"
mkdir -p $moduldir
#kicsomagolás és belépés
chmod +x $forras.run
./"$forras".run -x
mv $forras/* ./
rm $forras.*
patch -Np1 < "$UB_SRCDIR"/patches/nvidia-json.skip
cd kernel
if [ "$UB_ARCH" == "i386" ];then
    sed /phys_to_dma/d -i nvidia/nvidia.Kbuild
fi
make SYSSRC=/usr/src/linux-$KVER KERNEL_UNAME="$KVER" MODULE_ROOT=$moduldir module
cd ..
export NV_USE_BUNDLED_LIBJANSSON=0
alprogi settings
alprogi xconfig
alprogi modprobe
alprogi persistenced
