#!/bin/sh -eux

dpkg-deb -x ghetto-skype_${UB_VERSION}_${UB_ARCH}.deb .
rm -f ghetto-skype_${UB_VERSION}_*.deb

patch -p1 -i $UB_SRCDIR/patches/desktop.patch.skip
patch -p1 -i $UB_SRCDIR/patches/browser.patch.skip

cp -r "$UB_COMPILEDIR"/usr "$UB_INSTALLDIR"/
cp -r "$UB_COMPILEDIR"/opt/* "$UB_INSTALLDIR"/usr/lib/ghetto-skype

rm -Rf "$UB_INSTALLDIR"/usr/share/lintian

ln -s /usr/lib/ghetto-skype/ghetto-skype "$UB_INSTALLDIR"/usr/bin/ghetto-skype
