#!/bin/sh -eux

# users:
# coredump: systemd-coredump
# microhttpd: systemd-jornal-{gateway,remote}
# libcurl: systemd-jornal-upload
# --with-default-dnssec=no: a dnssec experimental

mv {usb,pci}.ids ma-{large,medium,small}.txt hwdb/

# a meson build nem készít .la fájlokat
./autogen.sh
ub_configure \
	--with-pamlibdir=/lib/security \
	--with-ntp-servers=pool.ntp.org \
	--with-default-dnssec=no \
	--enable-manpages \
	--enable-split-usr \
	--disable-libcurl \
	--disable-microhttpd \
	--disable-coredump
ub_make

#ub_compile \
#	-Dkill-path=/bin/kill \
#	-Dpamlibdir=/lib/security \
#	-Dntp-servers=pool.ntp.org \
#	-Ddefault-dnssec=no \
#	-Dlink-udev-shared=true \
#	-Dsplit-usr=false \
#	-Dlibcurl=false \
#	-Dmicrohttpd=false \
#	-Dcoredump=false

cd hwdb
./ids-update.pl
