#!/bin/sh -eux

# users:
# coredump: systemd-coredump
# microhttpd: systemd-jornal-{gateway,remote}
# libcurl: systemd-jornal-upload
# --with-default-dnssec=no: a dnssec experimental

mv {usb,pci}.ids ma-{large,medium,small}.txt hwdb/

rm -f autogen.sh

ub_compile \
	-Dkill-path=/bin/kill \
	-Dpamlibdir=/lib/security \
	-Dntp-servers=pool.ntp.org \
	-Ddefault-dnssec=no \
	-Dsplit-usr=false \
	-Dlibcurl=false \
	-Dmicrohttpd=false \
	-Dcoredump=false

cd hwdb
./ids-update.pl
