#!/bin/sh -eux

ub_install
# Külön csomag lesz, amit a júzernek majd letölt a postinst stkript
rm -rf ${UB_INSTALLDIR}/usr/share/openmortal
#verzió a letöltő postinstbe
sed "s/ubversion/$UB_VERSION/" -i $UB_SRCDIR/packages/openmortal-data/postinst
