#!/bin/sh -eux

# build from source
if [ "$UB_ARCH" == "amd64" ]; then
	hostflags=(
	--build=x86_64-unknown-linux-gnu
	--host=x86_64-unknown-linux-gnu
	--target=x86_64-unknown-linux-gnu
	)
else
	hostflags=(
	--build=i686-unknown-linux-gnu
	--host=i686-unknown-linux-gnu
	--target=i686-unknown-linux-gnu
	)
fi

./configure \
	--prefix=${UB_INSTALLDIR}/usr \
	--llvm-root=/usr \
	--enable-llvm-link-shared \
	${hostflags[@]}

./x.py build \
	${hostflags[@]}
