#!/bin/sh -eux

LDFLAGS="-Wl,--as-needed"
export RUSTFLAGS+="-L $UB_INSTALLDIR/usr/lib -C link-args=$LDFLAGS"

./x.py install

rm -f $UB_INSTALLDIR/usr/lib/liblzma.{a,la}
rm -f $UB_INSTALLDIR/usr/lib/pkgconfig/liblzma.pc
rm -f $UB_INSTALLDIR/usr/lib/rustlib/{components,install.log,manifest-*,rust-installer-version,uninstall.sh}
rm -Rf $UB_INSTALLDIR/usr/include
rm -Rf $UB_INSTALLDIR/usr/share/doc/rust
