#!/bin/bash -eux

kernelsrc64="$(echo /lib/modules/*.x86_64/build)"
kernelsrc32="$(echo /lib/modules/*.i386/build)"

if [ $UB_ARCH = "amd64" ]; then
	hostflags=(
		--target-arch=amd64
		--target-cpu=k8
		--with-linux=$kernelsrc64
	)
else
	hostflags=(
		--target-arch=x86
		--target-cpu=i686
		--with-linux=$kernelsrc32
	)
fi

# --disable-vmmraw: disable building 32-bit guest additions iso
./configure \
	--disable-hardening \
	--disable-java \
	--disable-docs \
	--disable-vmmraw \
	${hostflags[@]}

source ./env.sh
kmk all

if [ $UB_ARCH = "amd64" ]; then
	cd ./out/linux.amd64/release/bin/src
	ub_make KERN_DIR=$kernelsrc64
else
	cd ./out/linux.x86/release/bin/src
	ub_make KERN_DIR=$kernelsrc32
fi
